# include = "local_config.toml"

[env]
ESP_IDF_PATH_ISSUES = "warn"
ESP_IDF_VERSION = { value = "tag:v5.3.1" } # Was 5.2.1
ESP_LOG="info"
ESP_IDF_TOOLS_INSTALL_DIR = "custom:D:\\.esp"

[net]
git-fetch-with-cli = true

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --partition-table partitions.csv --target-app-partition factory"
rustflags = [ "-C", "link-arg=-nostartfiles", "--cfg", "espidf_time64", "--cfg", "mio_unsupported_force_poll_poll", "--cfg", "has_std", "-Z", "threads=8"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --partition-table partitions.csv --target-app-partition factory"
rustflags = ["-C", "link-arg=-nostartfiles", "--cfg", "espidf_time64", "--cfg", "mio_unsupported_force_poll_poll", "--cfg", "has_std", "-Z", "threads=8", "--cfg", "getrandom_backend=\"esp_idf\""]